name: Build CDC Build Server (stub)
on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string
jobs:
  permissions:
    contents: read
    id-token: write
    packages: read
    
  stub:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Would build cdc-build-server for ${{ inputs.environment-name }}"
